version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python3.6 manage.py runserver 0.0.0.0:8000"
    container_name: prevencion_service
    volumes:
      - .:/prevencion_service
    ports:
      - "8000:8000"
